### ISSUE TITLE
qhud doesnt start

### ISSUE THREAD

**Issue by Smeagol001** [vmv/qHUD#1]
nformationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei qHUD.Hud.ExternalOverlay.<OnLoad>d__14.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by vmv** [comment]
Install this and try again after: [https://www.microsoft.com/en-us/download/details.aspx?id=49981](url)

**Comment by Smeagol001** [comment]
installer says  its allready installed
strange seems windowsupdate did something since yesterday i updated and b4 that hud worked nice

**Comment by vmv** [comment]
Use the forum for this if you didn't fix it yet: [http://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/553402-poehud-slim.html].
Thanks.
